apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: system
spec:
  selector:
    control-plane: dns-controller
  externalTrafficPolicy: Local
  ports:
  - port: 53
    protocol: UDP
    name: dns-udp
  - port: 53
    protocol: TCP
    name: dns-tcp
  type: LoadBalancer
