apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
spec:
  template:
    spec:
      containers:
      - name: manager
        args:
        - --enable-leader-election
        - --provider=ovh
        - --enable-webhook
        env:
        - name: OVH_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: provider-credentials
              key: endpoint
        - name: OVH_APPLICATION_KEY
          valueFrom:
            secretKeyRef:
              name: provider-credentials
              key: application-key
        - name: OVH_APPLICATION_SECRET
          valueFrom:
            secretKeyRef:
              name: provider-credentials
              key: application-secret
        - name: OVH_CONSUMER_KEY
          valueFrom:
            secretKeyRef:
              name: provider-credentials
              key: consumer-key
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: webhook-server-cert

