apiVersion: v1
kind: Service
metadata:
  name: dns-server
  namespace: dns-system
spec:
  externalTrafficPolicy: Local
  ports:
  - name: dns-udp
    port: 53
    protocol: UDP
  - name: dns-tcp
    port: 53
    protocol: TCP
  selector:
    control-plane: dns-controller
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: dns-controller
  name: dns-controller-manager
  namespace: dns-system
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: dns-controller
  template:
    metadata:
      labels:
        control-plane: dns-controller
    spec:
      containers:
      - args:
        - --enable-leader-election
        - --provider=coredns
        - --dns-log
        - --dns-forward=8.8.8.8
        - --dns-any
        - --enable-webhook
        command:
        - /k8s-dns
        image: linkacloud/k8s-dns-manager:v0.2.0
        name: manager
        ports:
        - containerPort: 53
          name: dns-udp
          protocol: UDP
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
      terminationGracePeriodSeconds: 10
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: webhook-server-cert
