apiVersion: v1
kind: Secret
metadata:
  name: dns-provider-credentials
  namespace: dns-system
stringData:
  organization-id: ${SCALEWAY_ORGANIZATION_ID}
  secret-key: ${SCALEWAY_SECRET_KEY}
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: dns-controller
  name: dns-controller-manager
  namespace: dns-system
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: dns-controller
  template:
    metadata:
      labels:
        control-plane: dns-controller
    spec:
      containers:
      - args:
        - --enable-leader-election
        - --provider=scaleway
        - --enable-webhook>
        command:
        - /k8s-dns
        env:
        - name: SCALEWAY_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: secret-key
              name: dns-provider-credentials
        - name: SCALEWAY_ORGANIZATION_ID
          valueFrom:
            secretKeyRef:
              key: organization-id
              name: dns-provider-credentials
        image: linkacloud/k8s-dns-manager:v0.1.2
        name: manager
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
      terminationGracePeriodSeconds: 10
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: webhook-server-cert
