apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: dns-controller
  name: dns-controller-manager
  namespace: dns-system
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: dns-controller
  template:
    metadata:
      labels:
        control-plane: dns-controller
    spec:
      containers:
      - args:
        - --enable-leader-election
        - --dns-log
        - --dns-forward=8.8.8.8
        - --dns-any
        command:
        - /k8s-dns
        image: linkacloud/k8s-dns-manager:latest
        name: manager
        ports:
        - containerPort: 53
          protocol: UDP
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
      terminationGracePeriodSeconds: 10
